import { useEffect, type ReactNode } from "react";
import insideLineLogo from "@/assets/icon-insideline.svg";
import "@fontsource-variable/dm-sans/index.css";
import "@fontsource/instrument-serif/400.css";
import "./print.css";

interface PrintLayoutProps {
  ready: boolean;
  children: ReactNode;
}

declare global {
  interface Window {
    __PRINT_READY__?: boolean;
  }
}

export function PrintLayout({ ready, children }: PrintLayoutProps) {
  useEffect(() => {
    // Only toggle body class on real /print/* routes. When rendered inside a
    // hidden container already tagged `.print-mode` (PDF export path), skip
    // body mutation so the visible app doesn't reflow.
    if (document.querySelector(".print-mode")) return;
    document.body.classList.add("print-mode");
    // Force light theme on print routes regardless of system or stored preference.
    const root = document.documentElement;
    const hadDark = root.classList.contains("dark");
    root.classList.remove("dark");
    root.classList.add("light");
    root.style.colorScheme = "light";
    return () => {
      document.body.classList.remove("print-mode");
      if (hadDark) {
        root.classList.remove("light");
        root.classList.add("dark");
        root.style.colorScheme = "dark";
      }
    };
  }, []);

  useEffect(() => {
    if (!ready) return;
    let cancelled = false;
    const markReady = async () => {
      try {
        if (document.fonts && document.fonts.ready) {
          await document.fonts.ready;
        }
      } catch {
        // ignore font-readiness errors
      }
      // Double rAF ensures React commits + layout + paints before signaling.
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          if (!cancelled) {
            window.__PRINT_READY__ = true;
          }
        });
      });
    };
    markReady();
    return () => {
      cancelled = true;
    };
  }, [ready]);

  return <div className="print-root">{children}</div>;
}

export function PrintPage({ children, className }: { children: ReactNode; className?: string }) {
  return <section className={`print-page ${className ?? ""}`}>{children}</section>;
}

interface PrintCoverProps {
  title: string;
  startupName: string;
  stage?: string | null;
  generatedAt?: Date;
  subtitle?: string;
  generatedBy?: string | null;
  score?: number;
  logoUrl?: string;
}

export function PrintCover({ title, startupName, stage, generatedAt, subtitle, generatedBy, score, logoUrl }: PrintCoverProps) {
  const date = (generatedAt ?? new Date()).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const formattedStage = stage
    ? stage
        .split("_")
        .filter(Boolean)
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
        .join(" ")
    : null;

  return (
    <section className="print-page print-cover">
      <div className="print-cover__top">
        <div className="print-cover__brand">
          <img src={insideLineLogo} alt="Inside Line" className="print-cover__brand-icon" />
          <span className="print-cover__brand-text">Inside Line</span>
        </div>
        <div className="print-cover__hero-split">
          <div className="print-cover__title-block">
            <p className="print-cover__kicker">{title}</p>
            <p className="print-cover__company-hero">{startupName}</p>
            {subtitle ? <p className="print-cover__subtitle">{subtitle}</p> : null}
          </div>
          <div className="print-cover__aside-hero">
            {logoUrl ? <img src={logoUrl} alt={`${startupName} logo`} className="print-cover__logo" /> : null}
            {score !== undefined ? (
              <div className="print-cover__score-card" aria-label={`Overall score ${Math.round(score)} out of 100`}>
                <span className="print-cover__score-caption">Overall score</span>
                <div className="print-cover__score print-cover__score--hero">
                  <span className="print-cover__score-value">{Math.round(score)}</span>
                  <span className="print-cover__score-scale">/100</span>
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </div>

      <div className="print-cover__bottom">
        <div className="print-cover__meta">
          {formattedStage ? <span>Stage {formattedStage}</span> : null}
          <span>Generated {date}</span>
          {generatedBy ? <span>Generated by {generatedBy}</span> : null}
        </div>
      </div>
    </section>
  );
}
