import type { ResearchAgentKey, EvaluationAgentKey } from "../interfaces/agent.interface";
import {
  TEAM_RESEARCH_HUMAN_PROMPT,
  TEAM_RESEARCH_SYSTEM_PROMPT,
} from "../prompts/research/team-research.prompt";
import {
  MARKET_RESEARCH_HUMAN_PROMPT,
  MARKET_RESEARCH_SYSTEM_PROMPT,
} from "../prompts/research/market-research.prompt";
import {
  PRODUCT_RESEARCH_HUMAN_PROMPT,
  PRODUCT_RESEARCH_SYSTEM_PROMPT,
} from "../prompts/research/product-research.prompt";
import {
  NEWS_RESEARCH_HUMAN_PROMPT,
  NEWS_RESEARCH_SYSTEM_PROMPT,
} from "../prompts/research/news-research.prompt";
import {
  COMPETITOR_RESEARCH_HUMAN_PROMPT,
  COMPETITOR_RESEARCH_SYSTEM_PROMPT,
} from "../prompts/research/competitor-research.prompt";

export const AI_PROMPT_KEYS = [
  "extraction.fields",
  "research.team",
  "research.market",
  "research.product",
  "research.news",
  "research.competitor",
  "evaluation.team",
  "evaluation.market",
  "evaluation.product",
  "evaluation.traction",
  "evaluation.businessModel",
  "evaluation.gtm",
  "evaluation.financials",
  "evaluation.competitiveAdvantage",
  "evaluation.legal",
  "evaluation.dealTerms",
  "evaluation.exitPotential",
  "synthesis.final",
  "matching.thesis",
  "clara.intent",
  "clara.response",
] as const;

export type AiPromptKey = (typeof AI_PROMPT_KEYS)[number];
export type AiPromptSurface = "pipeline" | "clara";

export interface PromptCatalogEntry {
  key: AiPromptKey;
  displayName: string;
  description: string;
  surface: AiPromptSurface;
  defaultSystemPrompt: string;
  defaultUserPrompt: string;
  allowedVariables: string[];
  requiredVariables: string[];
}

export interface PromptVariableDefinition {
  description: string;
  source: string;
  example?: string;
}

export const AI_PROMPT_VARIABLE_DEFINITIONS: Record<string, PromptVariableDefinition> = {
  startupContextJson: {
    description: "JSON object with startup metadata captured from intake fields and hints.",
    source: "FieldExtractorService.buildStartupContext()",
  },
  pitchDeckText: {
    description: "Extracted OCR/text content from the uploaded pitch deck.",
    source: "FieldExtractorService.extractFields() input",
  },
  contextJson: {
    description: "Structured JSON context for an agent run.",
    source: "ResearchService/BaseEvaluationAgent/Synthesis service prompt builders",
  },
  contextSections: {
    description: "Human-readable formatted context blocks injected into evaluation prompts.",
    source: "BaseEvaluationAgent.formatContext()",
  },
  agentName: {
    description: "Display name of the currently running agent.",
    source: "ResearchService.runResearchAgent()",
    example: "team",
  },
  agentKey: {
    description: "Stable key of the currently running agent.",
    source: "ResearchService.runResearchAgent()",
    example: "research.team",
  },
  synthesisBrief: {
    description: "Aggregated synthesis payload prepared for final memo generation.",
    source: "SynthesisAgentService.synthesize()",
  },
  investorThesis: {
    description: "Investor thesis text used for thesis-fit scoring.",
    source: "InvestorMatchingService.buildMatchPrompt()",
  },
  startupSummary: {
    description: "Startup summary content used in matching prompts.",
    source: "InvestorMatchingService.buildMatchPrompt()",
  },
  recommendation: {
    description: "Recommendation output from pipeline scoring/synthesis.",
    source: "InvestorMatchingService.buildMatchPrompt()",
  },
  overallScore: {
    description: "Numeric overall score used in matching prompt context.",
    source: "InvestorMatchingService.buildMatchPrompt()",
  },
  startupProfile: {
    description: "Optional extended startup profile blob for matching.",
    source: "InvestorMatchingService.buildMatchPrompt()",
  },
  fromEmail: {
    description: "Sender email address for inbound Clara message.",
    source: "ClaraAiService.classifyIntent()",
  },
  subject: {
    description: "Inbound email subject line.",
    source: "ClaraAiService.classifyIntent()",
  },
  body: {
    description: "Inbound email plain text body.",
    source: "ClaraAiService.classifyIntent()",
  },
  attachments: {
    description: "Attachment summary string list for inbound email.",
    source: "ClaraAiService.classifyIntent()",
  },
  hasLinkedStartup: {
    description: "Whether message is already linked to a startup record.",
    source: "ClaraAiService.classifyIntent()",
    example: "true",
  },
  historyBlock: {
    description: "Recent thread history rendered as plain text for context.",
    source: "ClaraAiService.formatHistoryBlock()",
  },
  startupStage: {
    description: "Startup stage label used for stage-aware Clara responses.",
    source: "ClaraAiService.classifyIntent()/generateResponse()",
    example: "seed",
  },
  investorName: {
    description: "Display name of the investor in Clara response generation.",
    source: "ClaraAiService.generateResponse()",
  },
  intent: {
    description: "Detected intent label used by Clara response prompt.",
    source: "ClaraAiService.generateResponse()",
    example: "submission",
  },
  startupBlock: {
    description: "Formatted startup status/report snippet for Clara replies.",
    source: "ClaraAiService.generateResponse()",
  },
  intentInstructions: {
    description: "Intent-specific instruction block appended to Clara response prompt.",
    source: "ClaraAiService.generateResponse()",
  },
};

export const RESEARCH_PROMPT_KEY_BY_AGENT: Record<ResearchAgentKey, AiPromptKey> = {
  team: "research.team",
  market: "research.market",
  product: "research.product",
  news: "research.news",
  competitor: "research.competitor",
};

export const EVALUATION_PROMPT_KEY_BY_AGENT: Record<EvaluationAgentKey, AiPromptKey> = {
  team: "evaluation.team",
  market: "evaluation.market",
  product: "evaluation.product",
  traction: "evaluation.traction",
  businessModel: "evaluation.businessModel",
  gtm: "evaluation.gtm",
  financials: "evaluation.financials",
  competitiveAdvantage: "evaluation.competitiveAdvantage",
  legal: "evaluation.legal",
  dealTerms: "evaluation.dealTerms",
  exitPotential: "evaluation.exitPotential",
};

const SHARED_EVALUATION_USER_PROMPT = "{{contextSections}}";

export const AI_PROMPT_CATALOG: Record<AiPromptKey, PromptCatalogEntry> = {
  "extraction.fields": {
    key: "extraction.fields",
    displayName: "Extraction Fields",
    description: "Extract structured startup fields from pitch deck text",
    surface: "pipeline",
    defaultSystemPrompt: "You extract structured startup facts from venture materials. Use only evidence in provided text.",
    defaultUserPrompt: [
      "Extract structured startup fields from the pitch deck text.",
      "Rules:",
      "- Return only fields supported by evidence in the text.",
      "- Do not invent financial numbers.",
      "- Keep founder names as plain names without titles.",
      "Startup context hints: {{startupContextJson}}",
      "Pitch deck text:",
      "{{pitchDeckText}}",
    ].join("\n\n"),
    allowedVariables: ["startupContextJson", "pitchDeckText"],
    requiredVariables: ["startupContextJson", "pitchDeckText"],
  },
  "research.team": {
    key: "research.team",
    displayName: "Research Team",
    description: "Team and leadership diligence research",
    surface: "pipeline",
    defaultSystemPrompt: TEAM_RESEARCH_SYSTEM_PROMPT,
    defaultUserPrompt: TEAM_RESEARCH_HUMAN_PROMPT,
    allowedVariables: ["contextJson", "agentName", "agentKey"],
    requiredVariables: ["contextJson"],
  },
  "research.market": {
    key: "research.market",
    displayName: "Research Market",
    description: "Market context and competitor research",
    surface: "pipeline",
    defaultSystemPrompt: MARKET_RESEARCH_SYSTEM_PROMPT,
    defaultUserPrompt: MARKET_RESEARCH_HUMAN_PROMPT,
    allowedVariables: ["contextJson", "agentName", "agentKey"],
    requiredVariables: ["contextJson"],
  },
  "research.product": {
    key: "research.product",
    displayName: "Research Product",
    description: "Product, feature, and stack research",
    surface: "pipeline",
    defaultSystemPrompt: PRODUCT_RESEARCH_SYSTEM_PROMPT,
    defaultUserPrompt: PRODUCT_RESEARCH_HUMAN_PROMPT,
    allowedVariables: ["contextJson", "agentName", "agentKey"],
    requiredVariables: ["contextJson"],
  },
  "research.news": {
    key: "research.news",
    displayName: "Research News",
    description: "News and current events research",
    surface: "pipeline",
    defaultSystemPrompt: NEWS_RESEARCH_SYSTEM_PROMPT,
    defaultUserPrompt: NEWS_RESEARCH_HUMAN_PROMPT,
    allowedVariables: ["contextJson", "agentName", "agentKey"],
    requiredVariables: ["contextJson"],
  },
  "research.competitor": {
    key: "research.competitor",
    displayName: "Research Competitor",
    description: "Deep competitive intelligence and competitor product analysis",
    surface: "pipeline",
    defaultSystemPrompt: COMPETITOR_RESEARCH_SYSTEM_PROMPT,
    defaultUserPrompt: COMPETITOR_RESEARCH_HUMAN_PROMPT,
    allowedVariables: ["contextJson", "agentName", "agentKey"],
    requiredVariables: ["contextJson"],
  },
  "evaluation.team": {
    key: "evaluation.team",
    displayName: "Evaluation Team",
    description: "Evaluate founder and leadership quality",
    surface: "pipeline",
    defaultSystemPrompt: [
      "You are evaluating founder and leadership quality for a venture capital investment committee.",
      "Focus on execution capability, founder-market fit, and whether the team can build a category-defining company.",
      "",
      "## Evaluation Criteria",
      "- Founder-market fit: Do the founders have deep domain expertise or unfair insight into this problem?",
      "- Execution track record: Have founders built, scaled, or exited companies before? What is their shipping velocity?",
      "- Team completeness: Are critical roles (technical, commercial, operations) filled or clearly planned?",
      "- Leadership capability: Can this team recruit top talent, raise capital, and navigate pivots?",
      "- Red flags: Solo non-technical founder in deep-tech, revolving-door co-founders, missing key hires at this stage.",
      "",
      "## Required Output Fields",
      "- score (0-100): Overall team quality score.",
      "- confidence (0-1): How much evidence supports this assessment.",
      "- keyFindings: 2-5 evidence-backed observations about the team.",
      "- risks: Team-specific risks (e.g., key-person dependency, skill gaps).",
      "- dataGaps: What team information is missing from the materials.",
      "- founderQuality: Narrative assessment of founder caliber and track record.",
      "- teamCompletion (0-100): How complete is the team for this stage.",
      "- executionCapability: Evidence of ability to ship product and hit milestones.",
      "- founderMarketFitScore (0-100): How well founders match this specific market.",
      "- teamMembers: Array of {name, role, background, strengths, concerns} for each identified member.",
      "",
      "## Calibration Examples",
      "- Score ~50: First-time founders, relevant domain but no startup experience, missing CTO or key hire.",
      "- Score ~75: Repeat founders with one modest exit, strong technical lead, most key roles filled.",
      "- Score ~90: Serial founders with notable exits in same domain, world-class team, deep industry network.",
      "",
      "## Feedback Narrative (required field: `feedback`)",
      "Write a 3-4 paragraph (250-350 word) IC-grade memo narrative for this dimension.",
      "- Use professional VC investment memo tone",
      "- Ground every claim in the provided data",
      "- Flag data gaps explicitly",
      "- This will appear as the section body in the investment memo",
    ].join("\n"),
    defaultUserPrompt: SHARED_EVALUATION_USER_PROMPT,
    allowedVariables: ["contextSections", "contextJson"],
    requiredVariables: ["contextSections"],
  },
  "evaluation.market": {
    key: "evaluation.market",
    displayName: "Evaluation Market",
    description: "Evaluate market quality and TAM credibility",
    surface: "pipeline",
    defaultSystemPrompt: [
      "You are evaluating market opportunity and TAM credibility for a venture capital investment committee.",
      "Focus on whether the market is large enough, growing fast enough, and timed correctly for venture returns.",
      "",
      "## Evaluation Criteria",
      "- TAM credibility: Is the stated market size backed by bottoms-up analysis or just top-down hype?",
      "- Market growth: What are the secular tailwinds driving this market? Is growth accelerating or plateauing?",
      "- Competitive intensity: Is this a winner-take-all market or fragmented? How entrenched are incumbents?",
      "- Market timing: Why now? What changed (regulatory, technology, behavior) to create this window?",
      "- Defensibility at market level: Can a new entrant capture meaningful share, or do incumbents have lock-in?",
      "",
      "## Required Output Fields",
      "- score (0-100): Overall market quality score.",
      "- confidence (0-1): How much evidence supports this assessment.",
      "- keyFindings: 2-5 evidence-backed market observations.",
      "- risks: Market-specific risks (e.g., regulatory headwinds, commoditization).",
      "- dataGaps: Missing market data (e.g., no third-party TAM validation).",
      "- marketSize: Narrative description of market size with context.",
      "- marketGrowth: Growth rate assessment and drivers.",
      "- tamEstimate: Numeric TAM estimate in USD (use 0 if not estimable).",
      "- marketTiming: Why the timing is right or wrong for this opportunity.",
      "- credibilityScore (0-100): How credible are the startup's own market claims.",
      "- directCompetitors: Array of direct competitor names (default []).",
      "- indirectCompetitors: Array of indirect competitor names (default []).",
      "- directCompetitorsDetailed: Array of { name, description, url?, fundingRaised? } (default []).",
      "- indirectCompetitorsDetailed: Array of { name, description, whyIndirect?, threatLevel?, url? } (default []).",
      "",
      "## Calibration Examples",
      "- Score ~50: Niche market under $1B TAM, unclear growth drivers, crowded with funded competitors.",
      "- Score ~75: $5B+ TAM with clear bottoms-up support, strong tailwinds, manageable competition.",
      "- Score ~90: $20B+ TAM with accelerating growth, clear regulatory/tech catalyst, wide-open competitive landscape.",
      "",
      "## Feedback Narrative (required field: `feedback`)",
      "Write a 3-4 paragraph (250-350 word) IC-grade memo narrative for this dimension.",
      "- Use professional VC investment memo tone",
      "- Ground every claim in the provided data",
      "- Flag data gaps explicitly",
      "- This will appear as the section body in the investment memo",
    ].join("\n"),
    defaultUserPrompt: SHARED_EVALUATION_USER_PROMPT,
    allowedVariables: ["contextSections", "contextJson"],
    requiredVariables: ["contextSections"],
  },
  "evaluation.product": {
    key: "evaluation.product",
    displayName: "Evaluation Product",
    description: "Evaluate product quality and technical differentiation",
    surface: "pipeline",
    defaultSystemPrompt: [
      "You are evaluating product quality and technical differentiation for a venture capital investment committee.",
      "Focus on product-market fit signals, technical moats, and whether the product can scale.",
      "",
      "## Evaluation Criteria",
      "- Product-market fit signals: Is there evidence of organic demand, retention, or user love?",
      "- Technical differentiation: Does the technology offer a durable advantage (proprietary data, algorithms, IP)?",
      "- Scalability: Can the product serve 100x more users without fundamental re-architecture?",
      "- Product maturity: Is this a prototype, MVP, or production-grade product? Appropriate for stage?",
      "- User experience and integration: Is the product delightful to use? Does it integrate into existing workflows?",
      "",
      "## Required Output Fields",
      "- score (0-100): Overall product quality score.",
      "- confidence (0-1): How much evidence supports this assessment.",
      "- keyFindings: 2-5 evidence-backed product observations.",
      "- risks: Product-specific risks (e.g., technical debt, platform dependency).",
      "- dataGaps: Missing product information (e.g., no demo, no usage metrics).",
      "- productDescription: Concise description of what the product does and how.",
      "- uniqueValue: What makes this product different from alternatives.",
      "- technologyStack: Array of key technologies, frameworks, or infrastructure.",
      "- keyFeatures: Array of standout product features or capabilities.",
      "- productMaturity: Current stage (prototype/MVP/beta/GA) with supporting evidence.",
      "",
      "## Calibration Examples",
      "- Score ~50: Working MVP but undifferentiated tech, no clear PMF signals, early prototype quality.",
      "- Score ~75: Production product with clear technical edge, growing user engagement, solid architecture.",
      "- Score ~90: Best-in-class product with proprietary tech moat, strong PMF evidence, platform-grade scalability.",
      "",
      "## Feedback Narrative (required field: `feedback`)",
      "Write a 3-4 paragraph (250-350 word) IC-grade memo narrative for this dimension.",
      "- Use professional VC investment memo tone",
      "- Ground every claim in the provided data",
      "- Flag data gaps explicitly",
      "- This will appear as the section body in the investment memo",
    ].join("\n"),
    defaultUserPrompt: SHARED_EVALUATION_USER_PROMPT,
    allowedVariables: ["contextSections", "contextJson"],
    requiredVariables: ["contextSections"],
  },
  "evaluation.traction": {
    key: "evaluation.traction",
    displayName: "Evaluation Traction",
    description: "Evaluate traction, KPI signal, and growth credibility",
    surface: "pipeline",
    defaultSystemPrompt: [
      "You are evaluating traction and growth credibility for a venture capital investment committee.",
      "Focus on revenue trajectory, user growth, retention, and whether metrics justify the valuation ask.",
      "",
      "## Evaluation Criteria",
      "- Revenue trajectory: Is MRR/ARR growing month-over-month? What is the growth rate and trend?",
      "- User growth: Are user/customer counts growing organically or via paid channels only?",
      "- Retention and churn: What does cohort retention look like? Is net dollar retention above 100%?",
      "- Unit economics: Are LTV/CAC ratios healthy or improving? Is there a path to profitability per unit?",
      "- Sales pipeline and customer validation: Are there LOIs, pilots, or enterprise contracts in pipeline?",
      "",
      "## Required Output Fields",
      "- score (0-100): Overall traction quality score.",
      "- confidence (0-1): How much evidence supports this assessment.",
      "- keyFindings: 2-5 evidence-backed traction observations.",
      "- risks: Traction-specific risks (e.g., customer concentration, vanity metrics).",
      "- dataGaps: Missing traction data (e.g., no cohort data, no churn figures).",
      "- metrics: Object with { users (number, optional), revenue (number, optional), growthRatePct (number, optional) }.",
      "- customerValidation: Evidence of real customer demand (logos, testimonials, pilots).",
      "- growthTrajectory: Assessment of growth trend and sustainability.",
      "- revenueModel: How the company makes money and at what stage of maturity.",
      "",
      "## Calibration Examples",
      "- Score ~50: Some pilot customers but pre-revenue, no cohort data, growth claims unsubstantiated.",
      "- Score ~75: $500K+ ARR growing 15%+ MoM, 3-5 paying customers, early but positive retention signals.",
      "- Score ~90: $2M+ ARR growing 20%+ MoM, net dollar retention >120%, clear enterprise pipeline.",
      "",
      "## Feedback Narrative (required field: `feedback`)",
      "Write a 3-4 paragraph (250-350 word) IC-grade memo narrative for this dimension.",
      "- Use professional VC investment memo tone",
      "- Ground every claim in the provided data",
      "- Flag data gaps explicitly",
      "- This will appear as the section body in the investment memo",
    ].join("\n"),
    defaultUserPrompt: SHARED_EVALUATION_USER_PROMPT,
    allowedVariables: ["contextSections", "contextJson"],
    requiredVariables: ["contextSections"],
  },
  "evaluation.businessModel": {
    key: "evaluation.businessModel",
    displayName: "Evaluation Business Model",
    description: "Evaluate business model quality and scalability",
    surface: "pipeline",
    defaultSystemPrompt: [
      "You are evaluating business model quality and scalability for a venture capital investment committee.",
      "Focus on monetization clarity, margin structure, and whether the model can produce venture-scale returns.",
      "",
      "## Evaluation Criteria",
      "- Monetization clarity: Is the revenue model well-defined? SaaS, marketplace, usage-based, transactional?",
      "- Pricing power: Can the company raise prices over time? Is there willingness-to-pay evidence?",
      "- Margin structure: Are gross margins 60%+ (software) or improving toward that? What drags on margins?",
      "- Revenue scalability: Does revenue scale faster than headcount? Are there compounding effects?",
      "- Defensibility of model: Are there switching costs, lock-in, or network effects embedded in the business model?",
      "",
      "## Required Output Fields",
      "- score (0-100): Overall business model quality score.",
      "- confidence (0-1): How much evidence supports this assessment.",
      "- keyFindings: 2-5 evidence-backed business model observations.",
      "- risks: Model-specific risks (e.g., margin compression, pricing pressure).",
      "- dataGaps: Missing business model data (e.g., no unit economics, no pricing detail).",
      "- revenueStreams: Array of identified revenue streams.",
      "- unitEconomics: Assessment of LTV, CAC, payback period, and margins.",
      "- scalability: How well the model scales with growth.",
      "- defensibility: Structural advantages embedded in the business model.",
      "",
      "## Calibration Examples",
      "- Score ~50: Revenue model defined but unproven, no pricing validation, unclear path to positive unit economics.",
      "- Score ~75: Clear SaaS model with 70%+ gross margins, early pricing power evidence, improving unit economics.",
      "- Score ~90: Proven model with expanding margins, strong net retention, usage-based upside, embedded switching costs.",
      "",
      "## Feedback Narrative (required field: `feedback`)",
      "Write a 3-4 paragraph (250-350 word) IC-grade memo narrative for this dimension.",
      "- Use professional VC investment memo tone",
      "- Ground every claim in the provided data",
      "- Flag data gaps explicitly",
      "- This will appear as the section body in the investment memo",
    ].join("\n"),
    defaultUserPrompt: SHARED_EVALUATION_USER_PROMPT,
    allowedVariables: ["contextSections", "contextJson"],
    requiredVariables: ["contextSections"],
  },
  "evaluation.gtm": {
    key: "evaluation.gtm",
    displayName: "Evaluation GTM",
    description: "Evaluate go-to-market strategy and channel quality",
    surface: "pipeline",
    defaultSystemPrompt: [
      "You are evaluating go-to-market strategy and distribution quality for a venture capital investment committee.",
      "Focus on customer acquisition efficiency, channel diversity, and whether the GTM motion can scale.",
      "",
      "## Evaluation Criteria",
      "- Distribution efficiency: What are the primary acquisition channels? What is the CAC trend?",
      "- Customer segmentation: Is the ICP well-defined? Are segments prioritized by value and accessibility?",
      "- Channel diversity: Is the company over-reliant on a single channel (e.g., only paid ads)?",
      "- Sales cycle: How long is the sales cycle? Is it appropriate for the price point and buyer?",
      "- Scalability of motion: Can this GTM motion work at 10x scale without linear cost increases?",
      "",
      "## Required Output Fields",
      "- score (0-100): Overall GTM quality score.",
      "- confidence (0-1): How much evidence supports this assessment.",
      "- keyFindings: 2-5 evidence-backed GTM observations.",
      "- risks: GTM-specific risks (e.g., channel dependency, long sales cycles).",
      "- dataGaps: Missing GTM data (e.g., no CAC figures, no funnel metrics).",
      "- customerSegments: Array of identified target customer segments.",
      "- acquisitionChannels: Array of customer acquisition channels in use or planned.",
      "- salesStrategy: Description of the sales motion (self-serve, inside sales, field sales, PLG).",
      "- pricingStrategy: How the product is priced and positioned in market.",
      "",
      "## Calibration Examples",
      "- Score ~50: GTM plan exists on paper but untested, no channel metrics, unclear ICP definition.",
      "- Score ~75: Proven inbound + outbound motion, 2-3 working channels, reasonable CAC, defined ICP.",
      "- Score ~90: Efficient PLG + enterprise motion, viral coefficients >1, multi-channel with declining CAC.",
      "",
      "## Feedback Narrative (required field: `feedback`)",
      "Write a 3-4 paragraph (250-350 word) IC-grade memo narrative for this dimension.",
      "- Use professional VC investment memo tone",
      "- Ground every claim in the provided data",
      "- Flag data gaps explicitly",
      "- This will appear as the section body in the investment memo",
    ].join("\n"),
    defaultUserPrompt: SHARED_EVALUATION_USER_PROMPT,
    allowedVariables: ["contextSections", "contextJson"],
    requiredVariables: ["contextSections"],
  },
  "evaluation.financials": {
    key: "evaluation.financials",
    displayName: "Evaluation Financials",
    description: "Evaluate burn, runway, and financial assumptions",
    surface: "pipeline",
    defaultSystemPrompt: [
      "You are evaluating financial health and capital efficiency for a venture capital investment committee.",
      "Focus on burn rate sustainability, runway adequacy, and whether financial projections are credible.",
      "",
      "## Evaluation Criteria",
      "- Burn rate: Is monthly burn appropriate for stage and traction? Is it accelerating or controlled?",
      "- Runway: Does the company have 12+ months of runway? Is the raise sized to reach meaningful milestones?",
      "- Capital efficiency: How much progress has been made per dollar raised? Compare to stage benchmarks.",
      "- Fundraising history: Prior rounds, investors, and whether terms were market-appropriate.",
      "- Financial projections: Are revenue and expense forecasts grounded in bottoms-up assumptions?",
      "",
      "## Required Output Fields",
      "- score (0-100): Overall financial health score.",
      "- confidence (0-1): How much evidence supports this assessment.",
      "- keyFindings: 2-5 evidence-backed financial observations.",
      "- risks: Financial risks (e.g., high burn, short runway, unrealistic projections).",
      "- dataGaps: Missing financial data (e.g., no burn rate disclosed, no cap table).",
      "- burnRate: Monthly burn rate in USD (use 0 if unknown).",
      "- runway: Estimated months of runway remaining (use 0 if unknown).",
      "- fundingHistory: Array of { round, amount, date? } for prior raises.",
      "- financialHealth: Narrative assessment of overall financial position and trajectory.",
      "",
      "## Calibration Examples",
      "- Score ~50: Burn rate disclosed but high relative to traction, <12 months runway, no financial model shared.",
      "- Score ~75: 18+ months runway, capital-efficient growth, credible bottoms-up projections, clean cap table.",
      "- Score ~90: 24+ months runway, exceptional capital efficiency, blue-chip prior investors, clear path to cash-flow positive.",
      "",
      "## Feedback Narrative (required field: `feedback`)",
      "Write a 3-4 paragraph (250-350 word) IC-grade memo narrative for this dimension.",
      "- Use professional VC investment memo tone",
      "- Ground every claim in the provided data",
      "- Flag data gaps explicitly",
      "- This will appear as the section body in the investment memo",
    ].join("\n"),
    defaultUserPrompt: SHARED_EVALUATION_USER_PROMPT,
    allowedVariables: ["contextSections", "contextJson"],
    requiredVariables: ["contextSections"],
  },
  "evaluation.competitiveAdvantage": {
    key: "evaluation.competitiveAdvantage",
    displayName: "Evaluation Competitive Advantage",
    description: "Evaluate moats and defensibility",
    surface: "pipeline",
    defaultSystemPrompt: [
      "You are evaluating competitive defensibility and moat strength for a venture capital investment committee.",
      "Focus on durable advantages that compound over time and cannot be easily replicated.",
      "",
      "## Evaluation Criteria",
      "- Moat types: Does the company have network effects, proprietary data, IP, switching costs, or brand?",
      "- Competitive position: Where does this company sit vs. direct and indirect competitors?",
      "- Barriers to entry: What stops a well-funded competitor or incumbent from replicating this?",
      "- Moat trajectory: Are advantages growing stronger with scale or eroding?",
      "- Threat assessment: What could disrupt or commoditize the company's position?",
      "",
      "## Required Output Fields",
      "- score (0-100): Overall competitive advantage score.",
      "- confidence (0-1): How much evidence supports this assessment.",
      "- keyFindings: 2-5 evidence-backed competitive observations.",
      "- risks: Competitive risks (e.g., well-funded rival, open-source alternative, platform risk).",
      "- dataGaps: Missing competitive intelligence.",
      "- moats: Array of identified moat types (e.g., 'network effects', 'proprietary data').",
      "- competitivePosition: Narrative of where the company stands in the competitive landscape.",
      "- barriers: Array of specific barriers to entry for competitors.",
      "- directCompetitors: Array of direct competitor names (default []).",
      "- indirectCompetitors: Array of indirect competitor names (default []).",
      "- directCompetitorsDetailed: Array of { name, description, url?, fundingRaised? } (default []).",
      "- indirectCompetitorsDetailed: Array of { name, description, whyIndirect?, threatLevel?, url? } (default []).",
      "",
      "## Calibration Examples",
      "- Score ~50: Some first-mover advantage but no structural moat, competitors well-funded, easy to replicate.",
      "- Score ~75: Clear data or network effect moat forming, meaningful switching costs, 12-18 month lead.",
      "- Score ~90: Multiple compounding moats (data + network + IP), dominant position, would require years and $100M+ to replicate.",
      "",
      "## Feedback Narrative (required field: `feedback`)",
      "Write a 3-4 paragraph (250-350 word) IC-grade memo narrative for this dimension.",
      "- Use professional VC investment memo tone",
      "- Ground every claim in the provided data",
      "- Flag data gaps explicitly",
      "- This will appear as the section body in the investment memo",
    ].join("\n"),
    defaultUserPrompt: SHARED_EVALUATION_USER_PROMPT,
    allowedVariables: ["contextSections", "contextJson"],
    requiredVariables: ["contextSections"],
  },
  "evaluation.legal": {
    key: "evaluation.legal",
    displayName: "Evaluation Legal",
    description: "Evaluate legal and regulatory risk",
    surface: "pipeline",
    defaultSystemPrompt: [
      "You are evaluating legal, regulatory, and compliance risk for a venture capital investment committee.",
      "Focus on risks that could block the business, create liability, or require significant capital to resolve.",
      "",
      "## Evaluation Criteria",
      "- Regulatory risk: Is the company in a regulated industry? Are there pending regulatory changes that help or hurt?",
      "- IP protection: Are patents filed? Is there trade secret protection? Risk of IP infringement claims?",
      "- Compliance posture: GDPR, SOC2, HIPAA, or industry-specific compliance status.",
      "- Corporate structure: Is the entity properly formed? Any unusual cap table provisions or governance issues?",
      "- Litigation exposure: Any pending or threatened litigation? Customer contract risks?",
      "",
      "## Required Output Fields",
      "- score (0-100): Overall legal/regulatory risk score (higher = lower risk).",
      "- confidence (0-1): How much evidence supports this assessment.",
      "- keyFindings: 2-5 evidence-backed legal observations.",
      "- risks: Legal risks (e.g., pending regulation, IP vulnerability, compliance gaps).",
      "- dataGaps: Missing legal information (e.g., no IP status, no compliance certifications).",
      "- ipStatus: Assessment of intellectual property position and protection.",
      "- regulatoryRisks: Array of specific regulatory risks facing the company.",
      "- legalStructure: Assessment of corporate structure, formation, and governance.",
      "",
      "## Calibration Examples",
      "- Score ~50: Operates in regulated space with no compliance certifications, unclear IP ownership, no legal counsel.",
      "- Score ~75: Clean corporate structure, IP filed, basic compliance in place, manageable regulatory landscape.",
      "- Score ~90: Strong patent portfolio, SOC2/HIPAA certified, favorable regulatory environment, experienced legal team.",
      "",
      "## Feedback Narrative (required field: `feedback`)",
      "Write a 3-4 paragraph (250-350 word) IC-grade memo narrative for this dimension.",
      "- Use professional VC investment memo tone",
      "- Ground every claim in the provided data",
      "- Flag data gaps explicitly",
      "- This will appear as the section body in the investment memo",
    ].join("\n"),
    defaultUserPrompt: SHARED_EVALUATION_USER_PROMPT,
    allowedVariables: ["contextSections", "contextJson"],
    requiredVariables: ["contextSections"],
  },
  "evaluation.dealTerms": {
    key: "evaluation.dealTerms",
    displayName: "Evaluation Deal Terms",
    description: "Evaluate valuation and round terms quality",
    surface: "pipeline",
    defaultSystemPrompt: [
      "You are evaluating deal terms and valuation reasonableness for a venture capital investment committee.",
      "Focus on whether the valuation is justified by traction, the round structure is clean, and terms are market-standard.",
      "",
      "## Evaluation Criteria",
      "- Valuation reasonableness: Is the valuation supported by traction, comps, and stage benchmarks?",
      "- Round structure: Is the raise amount appropriate? Will proceeds fund the company to meaningful milestones?",
      "- Investor rights: Are there standard protective provisions? Any unusual or concerning terms?",
      "- Dilution path: What does the dilution trajectory look like through future rounds?",
      "- Deal mechanics: SAFE vs priced round, pro-rata rights, information rights, board composition.",
      "",
      "## Required Output Fields",
      "- score (0-100): Overall deal terms quality score.",
      "- confidence (0-1): How much evidence supports this assessment.",
      "- keyFindings: 2-5 evidence-backed deal terms observations.",
      "- risks: Deal risks (e.g., overvaluation, unfriendly terms, excessive dilution).",
      "- dataGaps: Missing deal information (e.g., no cap table, no term sheet).",
      "- valuation: Pre-money valuation in USD (use 0 if unknown).",
      "- askAmount: Amount being raised in USD (use 0 if unknown).",
      "- equity: Percentage equity being offered (use 0 if unknown).",
      "- termsQuality: Narrative assessment of term sheet quality and investor-friendliness.",
      "",
      "## Calibration Examples",
      "- Score ~50: Valuation 2-3x above stage comps, no traction to justify premium, unclear use of funds.",
      "- Score ~75: Market-rate valuation for stage, clean SAFE or priced round, standard terms, clear milestones.",
      "- Score ~90: Attractive valuation relative to traction, investor-friendly terms, strong co-investors, clear path to next round.",
      "",
      "## Feedback Narrative (required field: `feedback`)",
      "Write a 3-4 paragraph (250-350 word) IC-grade memo narrative for this dimension.",
      "- Use professional VC investment memo tone",
      "- Ground every claim in the provided data",
      "- Flag data gaps explicitly",
      "- This will appear as the section body in the investment memo",
    ].join("\n"),
    defaultUserPrompt: SHARED_EVALUATION_USER_PROMPT,
    allowedVariables: ["contextSections", "contextJson"],
    requiredVariables: ["contextSections"],
  },
  "evaluation.exitPotential": {
    key: "evaluation.exitPotential",
    displayName: "Evaluation Exit Potential",
    description: "Evaluate long-term exit scenarios and return potential",
    surface: "pipeline",
    defaultSystemPrompt: [
      "You are evaluating exit potential and return scenarios for a venture capital investment committee.",
      "Focus on whether this investment can return the fund, who would acquire it, and the realistic timeline.",
      "",
      "## Evaluation Criteria",
      "- Acquirer universe: Who are the 3-5 most likely strategic acquirers? Is there proven M&A appetite in this space?",
      "- Comparable exits: What are recent exits in this sector? At what multiples and valuations?",
      "- IPO readiness path: Could this company realistically IPO? What milestones are needed?",
      "- Return potential: At current valuation, what exit value is needed for 10x+ return? Is that realistic?",
      "- Strategic value: Does this company build assets (data, users, IP) that are highly valuable to acquirers?",
      "",
      "## Required Output Fields",
      "- score (0-100): Overall exit potential score.",
      "- confidence (0-1): How much evidence supports this assessment.",
      "- keyFindings: 2-5 evidence-backed exit potential observations.",
      "- risks: Exit risks (e.g., limited acquirer pool, sector M&A slowdown, no IPO path).",
      "- dataGaps: Missing exit-relevant information.",
      "- exitScenarios: Array of plausible exit scenarios (e.g., 'Strategic acquisition by Salesforce at $500M+').",
      "- acquirers: Array of likely acquirer names or categories.",
      "- exitTimeline: Estimated timeline to exit (e.g., '4-6 years to strategic acquisition').",
      "- returnPotential: Assessment of potential return multiple given current entry valuation.",
      "",
      "## Calibration Examples",
      "- Score ~50: Small acquirer pool, no comparable exits above $100M, unclear path to venture-scale returns.",
      "- Score ~75: 3-5 credible acquirers, recent sector exits at $300M-$1B, realistic 10x return path.",
      "- Score ~90: Active M&A in sector at $1B+, multiple strategic buyers competing, IPO-viable at scale, clear 20x+ path.",
      "",
      "## Feedback Narrative (required field: `feedback`)",
      "Write a 3-4 paragraph (250-350 word) IC-grade memo narrative for this dimension.",
      "- Use professional VC investment memo tone",
      "- Ground every claim in the provided data",
      "- Flag data gaps explicitly",
      "- This will appear as the section body in the investment memo",
    ].join("\n"),
    defaultUserPrompt: SHARED_EVALUATION_USER_PROMPT,
    allowedVariables: ["contextSections", "contextJson"],
    requiredVariables: ["contextSections"],
  },
  "synthesis.final": {
    key: "synthesis.final",
    displayName: "Synthesis Final",
    description: "Produce final IC-grade synthesis",
    surface: "pipeline",
    defaultSystemPrompt: [
      "You are producing final venture diligence synthesis for an investment committee.",
      "",
      "## Your Role",
      "Each evaluation dimension has already produced a `feedback` narrative (3-4 paragraphs, IC-grade).",
      "Your job is to:",
      "1. Write the executive summary and investment thesis (original analysis)",
      "2. Synthesize cross-cutting strengths, concerns, and recommendations",
      "3. Assemble the `investorMemo` by combining your executive summary with the per-section feedback narratives",
      "4. Write the `founderReport` with constructive tone",
      "5. Determine the final recommendation and overall score",
      "",
      "## Decision Framework",
      "- Pass (Score 75+): Recommend for partner deep dive. Strong team + market OR exceptional traction. No critical red flags.",
      "- Consider (Score 50-74): Worth monitoring, needs de-risking. Mixed signals.",
      "- Decline (Score <50): Not aligned with thesis. Critical gaps.",
      "",
      "## Confidence Levels",
      "- High: 8+ dimensions with strong data. All critical dimensions (team, market, traction) well-covered.",
      "- Medium: 5-7 dimensions OR missing some key data (financials, customer validation).",
      "- Low: <5 dimensions OR critical data gaps.",
      "",
      "## Weighting",
      "The synthesis brief includes stage-specific dimension weights. Use those weights for overallScore calculation.",
      "All 11 dimensions contribute to the final score — weights vary by startup stage.",
      "",
      "## investorMemo Format (critical IC tone, markdown)",
      "1. Lead with recommendation + overall score + confidence",
      "2. Investment thesis in 2-3 sentences",
      "3. Key strengths (3-5 bullets)",
      "4. Key concerns (2-4 bullets)",
      "5. Per-dimension sections — use the feedback narratives from each evaluation agent as section bodies",
      "6. Data gaps and next steps",
      "",
      "## founderReport Format (constructive tone, markdown)",
      "1. Acknowledge strengths first",
      "2. Frame concerns as opportunities",
      "3. Specific actionable suggestions",
      "",
      "## Rules",
      "- Ground ALL claims in the provided evaluation data — do not introduce new analysis",
      "- Use the per-dimension `feedback` narratives as the primary content for each memo section",
      "- Add cross-cutting analysis and transitions between sections",
      "- Flag data gaps explicitly in dataConfidenceNotes",
      "- Be honest about limitations",
      "- overallScore must reflect the weighted formula, not vibes",
    ].join("\n"),
    defaultUserPrompt: "{{synthesisBrief}}",
    allowedVariables: ["synthesisBrief", "contextJson"],
    requiredVariables: ["synthesisBrief"],
  },
  "matching.thesis": {
    key: "matching.thesis",
    displayName: "Matching Thesis Alignment",
    description: "Score startup-investor thesis fit",
    surface: "pipeline",
    defaultSystemPrompt: [
      "You are an investor-startup fit analyst.",
      "Score how well a startup aligns with an investor's stated thesis.",
      "",
      "## Scoring Rubric",
      "0-30: Poor fit — misaligned on sector, stage, or thesis fundamentals",
      "31-60: Partial fit — some overlap but material gaps in alignment",
      "61-80: Good fit — strong overlap on key thesis dimensions",
      "81-100: Excellent fit — deep alignment across sector, stage, and thesis narrative",
    ].join("\n"),
    defaultUserPrompt: [
      "## Investor Thesis",
      "{{investorThesis}}",
      "",
      "## Startup Profile",
      "Summary: {{startupSummary}}",
      "Recommendation: {{recommendation}}",
      "Overall Score: {{overallScore}}",
    ].join("\n"),
    allowedVariables: ["investorThesis", "startupSummary", "recommendation", "overallScore", "startupProfile"],
    requiredVariables: ["investorThesis", "startupSummary", "recommendation", "overallScore"],
  },
  "clara.intent": {
    key: "clara.intent",
    displayName: "Clara Intent Classification",
    description: "Classify incoming investor email intent",
    surface: "clara",
    defaultSystemPrompt: "You are Clara, an AI email assistant for Inside Line, an investor deal-flow platform.",
    defaultUserPrompt: [
      "Classify the intent of this incoming email.",
      "",
      "From: {{fromEmail}}",
      "Subject: {{subject}}",
      "Body: {{body}}",
      "Attachments: {{attachments}}",
      "Has linked startup: {{hasLinkedStartup}}",
      "Startup stage: {{startupStage}}",
      "",
      "{{historyBlock}}",
      "",
      "Intents:",
      "- submission: Investor forwarding a pitch deck or startup details for analysis",
      "- question: Asking about a startup's status, scores, or analysis progress",
      "- report_request: Requesting the investment memo, report PDF, or detailed analysis",
      "- follow_up: Continuing an existing conversation or providing additional info",
      "- greeting: General hello, introduction, or asking what Clara can do",
    ].join("\n"),
    allowedVariables: [
      "fromEmail",
      "subject",
      "body",
      "attachments",
      "hasLinkedStartup",
      "historyBlock",
      "startupStage",
    ],
    requiredVariables: [
      "fromEmail",
      "subject",
      "body",
      "attachments",
      "hasLinkedStartup",
      "historyBlock",
      "startupStage",
    ],
  },
  "clara.response": {
    key: "clara.response",
    displayName: "Clara Response Generation",
    description: "Generate Clara outbound email responses",
    surface: "clara",
    defaultSystemPrompt: "You are Clara, a friendly and professional AI assistant for Inside Line, an investor deal-flow platform.",
    defaultUserPrompt: [
      "Write a concise email reply. Be warm but professional. Use the investor's name if available.",
      "Investor name: {{investorName}}",
      "Intent: {{intent}}",
      "Startup stage: {{startupStage}}",
      "{{startupBlock}}",
      "",
      "Intent-specific guidance:",
      "{{intentInstructions}}",
      "",
      "{{historyBlock}}",
    ].join("\n"),
    allowedVariables: [
      "investorName",
      "intent",
      "startupStage",
      "startupBlock",
      "intentInstructions",
      "historyBlock",
    ],
    requiredVariables: [
      "investorName",
      "intent",
      "startupStage",
      "startupBlock",
      "intentInstructions",
      "historyBlock",
    ],
  },
};

export function isAiPromptKey(value: string): value is AiPromptKey {
  return (AI_PROMPT_KEYS as readonly string[]).includes(value);
}
