/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedLayoutRouteImport } from './routes/_protected/_layout'
import { Route as ProtectedLayoutSettingsRouteImport } from './routes/_protected/_layout/settings'
import { Route as ProtectedLayoutDoneRouteImport } from './routes/_protected/_layout/done'
import { Route as ProtectedLayoutTodosIndexRouteImport } from './routes/_protected/_layout/todos.index'
import { Route as ProtectedLayoutTodosTodoIdRouteImport } from './routes/_protected/_layout/todos.$todoId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLayoutSettingsRoute = ProtectedLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutDoneRoute = ProtectedLayoutDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutTodosIndexRoute =
  ProtectedLayoutTodosIndexRouteImport.update({
    id: '/todos/',
    path: '/todos/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutTodosTodoIdRoute =
  ProtectedLayoutTodosTodoIdRouteImport.update({
    id: '/todos/$todoId',
    path: '/todos/$todoId',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/done': typeof ProtectedLayoutDoneRoute
  '/settings': typeof ProtectedLayoutSettingsRoute
  '/todos/$todoId': typeof ProtectedLayoutTodosTodoIdRoute
  '/todos/': typeof ProtectedLayoutTodosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/done': typeof ProtectedLayoutDoneRoute
  '/settings': typeof ProtectedLayoutSettingsRoute
  '/todos/$todoId': typeof ProtectedLayoutTodosTodoIdRoute
  '/todos': typeof ProtectedLayoutTodosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/_layout': typeof ProtectedLayoutRouteWithChildren
  '/_protected/_layout/done': typeof ProtectedLayoutDoneRoute
  '/_protected/_layout/settings': typeof ProtectedLayoutSettingsRoute
  '/_protected/_layout/todos/$todoId': typeof ProtectedLayoutTodosTodoIdRoute
  '/_protected/_layout/todos/': typeof ProtectedLayoutTodosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/done'
    | '/settings'
    | '/todos/$todoId'
    | '/todos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/done' | '/settings' | '/todos/$todoId' | '/todos'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/_layout'
    | '/_protected/_layout/done'
    | '/_protected/_layout/settings'
    | '/_protected/_layout/todos/$todoId'
    | '/_protected/_layout/todos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_layout': {
      id: '/_protected/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_layout/settings': {
      id: '/_protected/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedLayoutSettingsRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/done': {
      id: '/_protected/_layout/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof ProtectedLayoutDoneRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/todos/': {
      id: '/_protected/_layout/todos/'
      path: '/todos'
      fullPath: '/todos/'
      preLoaderRoute: typeof ProtectedLayoutTodosIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/todos/$todoId': {
      id: '/_protected/_layout/todos/$todoId'
      path: '/todos/$todoId'
      fullPath: '/todos/$todoId'
      preLoaderRoute: typeof ProtectedLayoutTodosTodoIdRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
  }
}

interface ProtectedLayoutRouteChildren {
  ProtectedLayoutDoneRoute: typeof ProtectedLayoutDoneRoute
  ProtectedLayoutSettingsRoute: typeof ProtectedLayoutSettingsRoute
  ProtectedLayoutTodosTodoIdRoute: typeof ProtectedLayoutTodosTodoIdRoute
  ProtectedLayoutTodosIndexRoute: typeof ProtectedLayoutTodosIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedLayoutDoneRoute: ProtectedLayoutDoneRoute,
  ProtectedLayoutSettingsRoute: ProtectedLayoutSettingsRoute,
  ProtectedLayoutTodosTodoIdRoute: ProtectedLayoutTodosTodoIdRoute,
  ProtectedLayoutTodosIndexRoute: ProtectedLayoutTodosIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
